sudo: required
services:
  - docker

before_install:
  - docker build -t govidiu20/vinyl-frontend-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true govidiu20/vinyl-frontend-test npm run test

after_success:
  - docker build -t govidiu20/vinyl-frontend-client ./client
  - docker build -t govidiu20/vinyl-frontend-nginx ./nginx
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" -- password-stdin
  - docker push govidiu20/vinyl-frontend-client
  - docker push govidiu20/vinyl-frontend-nginx

deploy:
  provider: elasticbeanstalk
  region: "eu-north-1"
  app: "vinyl-client"
  env: "Vinyl-client-env "
  bucket_name: "elasticbeanstalk-eu-north-1-589101405141"
  bucket_path: "vinyl-wade"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY