version: '3'

services:
  web:
    image: "govidiu20/vinyl-frontend-client"
    mem_limit: 128m
    hostname: web
  nginx:
    image: "govidiu20/vinyl-frontend-nginx"
    mem_limit: 128m
    hostname: nginx
    ports:
      - "80:80"
